name: Build and Deploy to production (cv.lukedekiewit.co.za)
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # 3. Cache Node modules.
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Install dependencies.
      - name: Install dependencies
        run: npm ci

      # 5. Build Astro project.
      - name: Build Astro
        run: npm run build

        # 6. Deploy incrementally and track removed files.
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 21
          local-dir: ./dist/
          server-dir: /cv.lukedekiewit.co.za/
          dry-run: false
          state-name: deployment.log
